

spring:
  application:
    name: feign-service


server:
  port: 9000
  

eureka:
  client:
    service-url:
      #defaultZone: http://eurekaserver1:8761/eureka/
      defaultZone: http://laibai:LaiBai2020@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}    



#endpoints:
#  shutdown:
#    enabled: true
#    sensitive: false
    